import { mockPlacesBerlin } from './mocks/mockPlacesBerlin'
import { mockPlacesZagreb } from './mocks/mockPlacesZagreb'

export const mockPlaces = [
  ...mockPlacesBerlin,
  ...mockPlacesZagreb,
  // {
  //   id: '1',
  //   host: 'James May',
  //   imageUrl: 'https://picsum.photos/id/10/300/300',
  //   details: 'Entire apartment',
  //   beds: '3',
  //   rating: '4.87',
  //   name: 'Cozy studio with balcony in Mitte',
  //   price: '$83',
  //   slides: [],
  //   country: 'USA',
  //   city: 'San Francisco',
  // },
  // {
  //   id: '2',
  //   host: 'James May',
  //   imageUrl: 'https://picsum.photos/id/101/300/300',
  //   details: 'Private room',
  //   beds: '1',
  //   rating: '4.23',
  //   name: 'Compact Queen Room',
  //   price: '$24',
  //   slides: [],
  //   country: 'USA',
  //   city: 'New York',
  // },
  // {
  //   id: '3',
  //   host: 'James May',
  //   imageUrl: 'https://picsum.photos/id/1015/300/300',
  //   details: 'Entire apartment',
  //   beds: '2',
  //   rating: '4.91',
  //   name: 'Modern studio in the hearth of City',
  //   price: '$48',
  //   slides: [],
  //   country: 'USA',
  //   city: 'San Francisco',
  // },
  // {
  //   id: '4',
  //   host: 'James May',
  //   imageUrl: 'https://picsum.photos/id/1016/300/300',
  //   details: 'Entire apartment',
  //   beds: '5',
  //   rating: '4.55',
  //   name: 'Amazing view of the city',
  //   price: '$39',
  //   slides: [],
  //   country: 'USA',
  //   city: 'New York',
  // },
  // {
  //   id: '5',
  //   host: 'James May',
  //   imageUrl: 'https://picsum.photos/id/1029/300/300',
  //   details: 'Entire apartment',
  //   beds: '1',
  //   rating: '4.19',
  //   name: 'Perfect resting stop',
  //   price: '$39',
  //   slides: [],
  //   country: 'Germany',
  //   city: 'Berlin',
  // },
  // {
  //   id: '6',
  //   host: 'James May',
  //   imageUrl: 'https://picsum.photos/id/1040/300/300',
  //   details: 'Private room',
  //   beds: '1',
  //   rating: '4.88',
  //   name: 'Castle Room',
  //   price: '$124',
  //   slides: [],
  //   country: 'Germany',
  //   city: 'Berlin',
  // },
  // {
  //   id: '7',
  //   host: 'James May',
  //   imageUrl: 'https://picsum.photos/id/10/300/300',
  //   details: 'Entire apartment',
  //   beds: '3',
  //   rating: '4.87',
  //   name: 'Cozy studio just step outside City Square',
  //   price: '$83',
  //   slides: [],
  //   country: 'USA',
  //   city: 'San Francisco',
  // },
  // {
  //   id: '8',
  //   host: 'James May',
  //   imageUrl: 'https://picsum.photos/id/101/300/300',
  //   details: 'Private room',
  //   beds: '1',
  //   rating: '4.23',
  //   name: 'Compact Queen Room',
  //   price: '$24',
  //   slides: [],
  //   country: 'USA',
  //   city: 'San Francisco',
  // },
  // {
  //   id: '9',
  //   host: 'James May',
  //   imageUrl: 'https://picsum.photos/id/1015/300/300',
  //   details: 'Entire apartment',
  //   beds: '2',
  //   rating: '4.91',
  //   name: 'Modern studio in the hearth of City',
  //   price: '$48',
  //   slides: [],
  //   country: 'USA',
  //   city: 'San Francisco',
  // },
  // {
  //   id: '10',
  //   host: 'James May',
  //   imageUrl: 'https://picsum.photos/id/1040/300/300',
  //   details: 'Private room',
  //   beds: '1',
  //   rating: '4.88',
  //   name: 'Castle Room',
  //   price: '$124',
  //   slides: [],
  //   country: 'USA',
  //   city: 'San Francisco',
  // },
]